- name: Environment setup
  hosts: all
  vars:
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
  tasks:
    - name: Install packages (apt)
      become: true
      apt:
        pkg: [git, zsh]
      when: is_debian

    - name: Instal packages (snap)
      become: true
      snap:
        name: [code, flameshot]
      when: is_debian

    - name: Install packages (brew)
      community.general.homebrew:
        name: git,zsh
        update_homebrew: yes
      when: is_macos

    - name: Install packages (brew cask)
      community.general.homebrew_cask:
        name: flameshot,visual-studio-code
      when: is_macos

    - name: Create folders
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.config/flameshot"

    - name: Create symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "~/{{ item.path }}"
        state: link
      with_community.general.filetree: dotfiles/
      when: item.state == 'file'
