- hosts: localhost
  connection: local
  tasks:
    - name: Check if .asdf folder exists
      stat: path="~/.asdf"
      register: asdf

    - when: not asdf.stat.exists
      name: Download asdf
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        depth: 1

    - name: Add execute permission to source script
      file:
        path: ~/.asdf/asdf.sh
        mode: 0755
      register: asdf_source

    - name: Get plugins to install
      shell: cat ~/.tool-versions | grep -v '^#' | awk '{print $1}'
      register: asdf_plugins

    - name: List installed plugins
      command: asdf plugin list
      register: asdf_installed_plugins

    - name: Add plugins that are not installed
      command: asdf plugin add {{ item }}
      when: item not in asdf_installed_plugins.stdout
      with_items: "{{ asdf_plugins.stdout_lines }}"

    - name: Install plugins versions
      command: asdf install
      args:
        chdir: ~
