- hosts: localhost
  connection: local
  vars:
    plugins:
      - name: java
        versions: [corretto-11.0.15.9.1, openjdk-17.0.2]
      - name: maven
        versions: [3.8.4]
      - name: nodejs
        versions: [14.19.2, 16.14.2, 17.5.0]
      - name: yarn
        versions: [1.22.18]
  tasks:
    - name: Check if .asdf folder exists
      stat: path="~/.asdf"
      register: asdf

    - when: not asdf.stat.exists
      block:
        - name: Install asdf
          git:
            repo: https://github.com/asdf-vm/asdf.git
            dest: ~/.asdf
            depth: 1

        - name: Install plugins
          command: asdf plugin add {{ item.name }}
          with_items: "{{ plugins }}"

        - name: Install plugins versions
          command: asdf install {{ item.0.name }} {{ item.1  }}
          with_subelements:
            - "{{ plugins }}"
            - versions
