- hosts: localhost
  connection: local
  vars:
    installer: /tmp/ohmyzsh-install.sh
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
  tasks:
    - name: Install packages (apt)
      become: true
      apt:
        pkg: [git, zsh, snapd, curl, vim, gh, docker.io]
      when: is_debian

    - name: Instal packages (snap)
      become: true
      snap:
        name: [code, flameshot]
      when: is_debian

    - name: Install packages (brew)
      community.general.homebrew:
        name: git,zsh,colima,curl,vim,gh,docker
        update_homebrew: yes
      when: is_macos

    - name: Install packages (brew cask)
      community.general.homebrew_cask:
        name: flameshot,visual-studio-code,docker,google-chrome
