- hosts: localhost
  connection: local
  tasks:
    - name: Read variables from file
      include_vars:
        file: "{{ playbook_dir }}/../variables.yaml"
        name: variables

    - name: Install macOS packages
      block:
        - name: Install taps
          community.general.homebrew_tap:
            name: "{{ variables.packages.brew.taps }}"

        - name: Install packages (brew)
          community.general.homebrew:
            name: "{{ variables.packages.brew.formula }}"
            update_homebrew: yes

        - name: Install packages (brew cask)
          community.general.homebrew_cask:
            name: "{{ variables.packages.brew.cask }}"

    - name: Install pip packages
      pip:
        name: "{{ variables.packages.pip }}"
