- hosts: localhost
  connection: local
  vars:
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
    google_chrome_installer: /tmp/google-chrome-stable.deb
  tasks:
    - name: Install packages (apt)
      become: true
      apt:
        pkg: [git, zsh, snapd, curl, vim, gh, docker.io, fonts-firacode, exa]
      when: is_debian

    - name: Instal packages (snap)
      become: true
      snap:
        name: [code, flameshot]
      when: is_debian

    - name: Install Google Chrome (debian)
      when: is_debian
      block:
        - name: Download Google Chrome
          get_url:
            url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dest: "{{ google_chrome_installer }}"

        - name: Install Google Chrome
          become: true
          apt:
            deb: "{{ google_chrome_installer }}"

        - name: Remove installer
          file:
            path: "{{ google_chrome_installer }}"
            state: absent

    - name: Install packages (brew)
      community.general.homebrew:
        name: git,zsh,colima,curl,vim,gh,docker,exa
        update_homebrew: yes
      when: is_macos

    - name: Install packages (brew cask)
      community.general.homebrew_cask:
        name: flameshot,visual-studio-code,docker,google-chrome,font-fira-code
