- hosts: localhost
  connection: local
  vars_prompt:
    - name: global_key_passphrase
      private: true
      prompt: Global SSH key passphrase
    - name: github_key_passphrase
      private: true
      prompt: GitHub SSH key passphrase
    - name: gitlab_key_passphrase
      private: true
      prompt: GitLab SSH key passphrase
  tasks:
    - name: Generate global SSH key
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_rsa"
        passphrase: "{{ global_key_passphrase }}"

    - name: Generate GitHub SSH key
      community.crypto.openssh_keypair:
        path: "~/.ssh/github"
        passphrase: "{{ github_key_passphrase }}"

    - name: Generate GitLab SSH key
      community.crypto.openssh_keypair:
        path: "~/.ssh/gitlab"
        passphrase: "{{ gitlab_key_passphrase }}"
