- hosts: localhost
  connection: local
  tasks:
    - name: Create folders
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.config/flameshot"

    - name: Create symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "~/{{ item.path }}"
        state: link
        force: true
      with_community.general.filetree: ../dotfiles/
      when: item.state == 'file'
